hydra:
  run:
    dir: logdir/${exp_id}/${seed}

exp_id: finfluencer
seed: 0
logdir: ${hydra:run.dir}
device: cuda
compile: True

# Inference
data_dir: /path/to/videos/
out_dir: /path/to/outputs/
batch_size: 32
xraw: 1024
yraw: 576
resize: 350
num_workers: 4

# Model
model:
  weights: path/to/weights/groundingdino_swint_ogc.pth
  dino_config: path/to/dino/repository/GroundingDINO/groundingdino/config/GroundingDINO_SwinT_OGC.py
  box_threshold: 0.4
  text_threshold: 0.25
  prompt: "laptop with clearly visible screen. text in video. number. company symbol. ticker symbol. line chart. bar chart. scatter plot"